apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    # ローカル開発のphpmyadmin用
    - host: himawari-phpmyadmin.dev
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: api-phpmyadmin-srv
              servicePort: 80
    - host: himawari.dev
      http:
        paths:
          - path: /swagger-json/?(.*)
            backend:
              serviceName: api-srv
              servicePort: 3000
          - path: /swagger/?(.*)
            backend:
              serviceName: api-srv
              servicePort: 3000
          - path: /api/?(.*)
            backend:
              serviceName: api-srv
              servicePort: 3000
          # ingress-nginxは、上からマッチするルートが選ばれる
          # client-srvは最後に置くこと！
          - path: /?(.*)
            backend:
              serviceName: client-srv
              servicePort: 3000
