apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    # プロダクションのdomain name
    - host: www.himawarigumi.xyz
      http:
        paths:
          # TODO: backend-srvの追加
          # ingress-nginxは、上からマッチするルートが選ばれる
          # client-srvは最後に置くこと！
          - path: /?(.*)
            backend:
              serviceName: client-srv
              servicePort: 3000
