name: test-node

on:
  pull_request:
    # 以下のディレクトリが変更されたPRのみ、このテストを実行
    paths:
      - "node/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd node && npm install && npm run test:ci
